### ISSUE TITLE
Bug on search 

### ISSUE THREAD

**Issue by darewealth** [mauriceoegerli/Monthh#1]
### Describe the bug
I clicked on the 3 dot icons by the right top, and clicked on the search, to search but the app crash. I felt it was a one-time thing, but the app kept crashing when I relaunched it and searched again

### Steps to reproduce.

* Launch the app.

* Clicked on the 3 dot icons by the right at the top

* Click on the search to search for anything and see the error.

### Expected Behaviour

I expected that I could search for anything on the application 

### Screen recording
https://youtu.be/lidsXvw76-I

### Devices and Versions):)

Device: [Itel]

Version [6.1]

App version [1.1]

### Log

``` 04-12 11:17:23.700 14340 14340 E AndroidRuntime: Process: com.maurice.monthh, PID: 14340
04-12 11:17:23.700 14340 14340 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ComponentName android.app.SearchableInfo.getSearchActivity()' on a null object reference
04-12 11:17:23.700 14340 14340 E AndroidRuntime: 	at com.android.calendar.CalendarController.launchSearch(CalendarController.java:639)
04-12 11:17:23.700 14340 14340 E AndroidRuntime: 	at com.android.calendar.CalendarController.sendEvent(CalendarController.java:444)
04-12 11:17:23.700 14340 14340 E AndroidRuntime: 	at com.android.calendar.CalendarController.sendEvent(CalendarController.java:255)
04-12 11:17:23.700 14340 14340 E AndroidRuntime: 	at com.android.calendar.CalendarController.sendEvent(CalendarController.java:239)
04-12 11:17:23.700 14340 14340 E AndroidRuntime: 	at com.android.calendar.AllInOneActivity.onQueryTextSubmit(AllInOneActivity.java:1410)
04-12 11:17:23.700 14340 14340 E AndroidRuntime: 	at android.support.v7.widget.SearchView.onSubmitQuery(SearchView.java:1190)
04-12 11:17:23.700 14340 14340 E AndroidRuntime: 	at android.support.v7.widget.SearchView$7.onEditorAction(SearchView.java:1167)
04-12 11:17:23.700 14340 14340 E AndroidRuntime: 	at android.widget.TextView.onEditorAction(TextView.java:4765)
04-12 11:17:23.700 14340 14340 E AndroidRuntime: 	at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:139)
04-12 11:17:23.700 14340 14340 E AndroidRuntime: 	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:304)
04-12 11:17:23.700 14340 14340 E AndroidRuntime: 	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
04-12 11:17:23.700 14340 14340 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-12 11:17:23.700 14340 14340 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
04-12 11:17:23.700 14340 14340 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5452)
04-12 11:17:23.700 14340 14340 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-12 11:17:23.700 14340 14340 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
04-12 11:17:23.700 14340 14340 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)```

**Comment by moisout** [comment]
Thank you very much for reporting this issue.
I will hopefully be able to provide a fix in the next update.
